### ISSUE TITLE
Question about full speed USB 2.0

### ISSUE THREAD

**Issue by AntonKrug** [avakar/usbcorev#4]
"This core allows you to embed a full-speed (12Mbps) USB 2.0 device core into your FPGA design."

What would be the difference between having a USB 1.1 core running full-speed vs USB 2.0?

https://en.wikipedia.org/wiki/USB#USB_1.x
https://en.wikipedia.org/wiki/USB#Receptacle_(socket)_identification

On the surface they look to me the same, wouldn't be simpler to make a USB 1.1 device then?

**Comment by avakar** [comment]
I'm guessing with respect to full-speed, USB 2.0 will be the same as 1.1, save maybe some clarification. However, I've only read the 2.0 specs, that's why I'm claiming 2.0 compatibility. I doubt there would be any difference in implementation.
